////////// PAGE WEB
String getPage() {
  //Fonction permettant d'obtenir tout le code HTML de la page host par l'appareil
char  pagePart1[] = 
"<!DOCTYPE html>\n"
"<html lang=\"fr\">\n"
"<script>\r\n"
"function process(){\r\n"
"var xhr = new XMLHttpRequest();\r\n"
"xhr.open('get', 'val.txt');\r\n"
"xhr.onreadystatechange = function(evt){\r\n"
"if(xhr.status==200 && xhr.readyState==4){\r\n"
"document.getElementById('val').innerHTML=xhr.responseText;\r\n"
"}\r\n"
"}\r\n"
"xhr.send(null);\r\n"
"setTimeout('process()',500);\r\n"
"}\r\n"
"</script>";
char  pagePart2[] = 
"<head>\n"
"<meta charset=\"utf-8\"/>\n"
"<title>BorneStationnement</title>\n"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n"
"<script type=\"text/javascript\" src=\"/F6217658-FE05-6447-9F09-CCC23686C489/main.js\" charset=\"UTF-8\"></script>\n"
"<style>header{display: flex;flex-direction: row;font-family: Courier New;padding: 20px 0 20px 0;background-color: #fff;}\n"
"body{display: flex;flex-direction: column;border-top: 1px solid #222538;border-left: 1px solid #222538;background-color: #ccc;}\n"
"li{padding: 10px 10px 10px 10px;background-color: rgb(0,80,162);list-style: none;}\n"
"li a{color: white;text-decoration: none;}\n"
"ul{display: flex;justify-content: space-around;text-decoration: none;}\n"
"nav{border-top: 1px solid #222538;border-bottom: 1px solid #222538;background-color: #ccc;}\n"
"nav li{padding: 10px 10px 10px 10px;background-color: rgb(0,80,162);list-style: none;border-radius: 2px;color: white;text-decoration: none;}\n"
"nav li:hover{background-color: #0066cc;}\n"
"section{row: 1;background-color: #fff;display: flex;flex-direction: row;padding-bottom:10px;}\n"
"p{flex: 1;text-align: justify;}\n"
"footer{padding: 20px 20px 20px 20px;background-color: #ccc;border-top: 1px solid #222538;}\n"
"h1{font-size: 4.5em;}\n"
"h2{font-size: 3.3em ;font-family: Courier New;background-color: #FFF;color: rgb(0,80,162);border-bottom: 2px solid red;border-right: 2px solid red;padding-left: 5px;width: 1;}\n"
"#pagetop{position: fixed;right: 25px;bottom: 0px;}\n"
"#photo{border: 1px solid black;margin-bottom: 20px;}\n"
"article{margin-left: 180px;padding-right: 10px;}\n"
"aside{position: fixed;float: left;left: 15px;top:250px;width: 150px;box-shadow: 6px 6px 6px #222538;}\n"
"</style>\n"
"</head>\n";
char  pagePart3[] = 
"<body onload='process()'>\n"
"  <!--lien  haut de page--><div id=\"hautdepage\"> </div>\n"
"<header>\n"
"<img src=\"https://www.informatiquegifs.com/actualites/images/france/image-de-police.jpg\" alt=\"La CNIL\" height=\"95px\" style=\"padding-left: 10px;\" >\n"
"</header>\n"
"<nav><ul>\n"
"<li><a href=\"Main.html\">Accueil</a></li>\n"
"<li><a href=\"Informations.html\">Historique des RFID</a></li>\n"
"<li><a href=\"Equipe.html\">L'équipe de choc du Projet</a></li>\n"
"</ul></nav>\n"
"<section>\n"
"<!--pour remonter en haut de page-->\n"
"<div id=\"pagetop\"><p><a href=\"#hautdepage\"><img src=\"images/verslehaut.png\" alt=\"Bouton haut de page\"/></a></p></div>\n"
"<!--menu interne à la page-->\n"
"<aside>\n"
"<li><a href=\"#Introduction\">Introduction</a></li>\n"
"<li><a href=\"#Utilisation du site\">Liste des Tags détectés</a></li>\n"
"</aside>\n"
"<article>\n"
"<h2 id=\"Introduction\">Introduction</h2>\n"
"<p>Bonjour,<Br/><Br/>Dans le cadre de la réalisation du POC 2 du projet borne de stationnement, nous avons réalisé un site internet permetant de démontrer les fonctionnalités attendues.<Br/>Ce site, hébergé par l'arduino, permet d'avoir accès à l'historique des tags RFID scannés.</p>\n"
"<h2 id=\"Utilisation du site\">Liste des Tags détectés</h2>\n""<p>\n"
"<span id='val'>En attente...</span><Br/><Br/><Br/><Br/><Br/><Br/><Br/><Br/><Br/><Br/>"
"</p>\n"
"</article>"
"</section>\n"
"<footer>\n"
"<p>Production maison de Gatien<br/>Tous droits r&eacute;serv&eacute;s<br/></p>"
"</footer>\n"
"</body>"
"</html>\n";
String pageStr = String(pagePart1)+String(pagePart2)+String(pagePart3);
  return pageStr;
}
